export const LK = {
  header: "lk-header",
  helperStatus: "helper-status",
  connectBtn: "open-setup-btn",
  midiLearnToggle: "midi-learn-toggle",
  profileSelect: "profile-select",
  newProfileBtn: "new-profile-btn",
  newProfileInput: "new-profile-input",
  newProfileSave: "new-profile-save",
  deleteProfileBtn: "delete-profile-btn",
  sessionsPanel: "sessions-panel",
  sessionItem: (name) => `session-${name}`,
  hardware: "hardware-visualizer",
  knob: (i) => `knob-${i}`,
  pad: (i) => `pad-${i}`,
  key: (i) => `key-${i}`,
  modWheel: "mod-wheel",
  pitchWheel: "pitch-wheel",
  transport: (k) => `transport-${k}`,
  trackUp: "track-up",
  trackDown: "track-down",
  sceneUp: "scene-up",
  sceneDown: "scene-down",
  mappingDialog: "mapping-dialog",
  mappingActionSelect: "mapping-action-select",
  mappingTargetSelect: "mapping-target-select",
  mappingTargetInput: "mapping-target-input",
  mappingSave: "mapping-save",
  mappingDelete: "mapping-delete",
  mappingLabel: "mapping-label",
  eventLog: "event-log",
  setupPage: "setup-page",
  downloadScript: "download-script-btn",
};
